version: "3.8"

services:
  db:
    image: mysql:8.0.32
    container_name: mysql_main
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: savvy_mhdspoje
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ../DB:/docker-entrypoint-initdb.d

  app:
    build:
      context: ../jrvnet/JrvNetMigration
      dockerfile: Dockerfile
    container_name: jrvnet_app
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    depends_on:
      - db

volumes:
  dbdata:
